Add color rule for INI syntax
facelessuser/ColorHelper pull request #264
Opened 2024-05-02 23:49 UTC by gosxrgxx

Support colors for .ini files

2024-05-07 12:58 UTC, facelessuser commented
Thanks for the pull, I'll try to evaluate it sometime soon.

2024-05-15 14:48 UTC, facelessuser commented
@gosxrgxx, I think you want a pattern more like:

```
(?i)(?:\\b(?<![-#&$])(?:color\\((?!\\s*-)|(?:hsla?|(?:ok)?(?:lch|lab)|hwb|rgba?)\\()|\\b(?<![-#&$])[\\w]{3,}(?![(-])\\b|(?<![&])\\#)
```

2024-05-15 14:49 UTC, facelessuser commented
I think that is the default pattern though, so you can just remove that pattern entry entirely.

2024-05-19 16:40 UTC, gosxrgxx commented
To exclude color names (green, red, etc.). Perhaps you can suggest a more suitable solution.

2024-05-19 17:16 UTC, facelessuser commented
When I'm adding such rules, I'm keeping them generic as everyone may want different things. INI files don't have innate color requirements.

2024-05-19 17:17 UTC, facelessuser commented
If a specific file type has a specific spec in relation to colors, that is generally when we are more selective.

2024-05-19 17:52 UTC, gosxrgxx commented
Ok. In that case, should I remove the line with the regular expression, or will you do it?

2024-05-19 19:59 UTC, facelessuser commented
Ideally, you could make the change in this PR.

2024-05-20 15:28 UTC, facelessuser requested changes
Everything looks fine except for the minor requested changes.

2024-05-20 15:28 UTC, facelessuser commented on color_helper.sublime-settings
> +            "base_scopes": ["source.ini",],
Please remove the dangling comma in the list

2024-05-20 15:28 UTC, facelessuser commented on color_helper.sublime-settings
> +            "scanning": ["meta.mapping.value.ini"],
Please remove the dangling comma on this line as well.

2024-05-20 16:05 UTC, facelessuser approved these changes

2024-05-20 16:05 UTC, facelessuser commented
@gir-bot lgtm

2024-05-20 16:06 UTC, merged